---
title: "p8105_hw6_nk2814"
author: "Naama Kipperman"
date: "11/21/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


#### Problem 1 

```{r}

# Import and clean birthweight data for regression analysis
# outcome = bwt

# Load and clean the data for regression analysis (i.e. convert numeric to factor where appropriate, check for missing data, etc.).


birthweight =
  read.csv("birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace),
    bwt = bwt/453.592   
  ) 

# Propose a regression model for birthweight. This model may be based on a hypothesized structure for the factors that underly birthweight, on a data-driven model-building process, or a combination of the two. Describe your modeling process and show a plot of model residuals against fitted values – use add_predictions and add_residuals in making this plot.


# First, fit a preliminary simple linear regression model, regressing maternal pre-pregnancy weight (lbs) on birthweight (lbs)

fit1 = lm(bwt ~ ppwt, data = birthweight) %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) 



```

